using ClosedXML.Excel;
using Intelibill.Application.Features.Exports.ProfitLoss;
using Intelibill.Application.Features.Exports.ProfitLoss.DTOs;
using System.Text.RegularExpressions;

namespace Intelibill.Infrastructure.Services.Exports;

public sealed class ProfitLossExcelExportRenderer : IProfitLossExcelExportRenderer
{
    public Task<ProfitLossExportResult> RenderAsync(ProfitLossExportDatasetDto dataset, CancellationToken cancellationToken)
    {
        using var workbook = new XLWorkbook();
        var worksheet = workbook.Worksheets.Add("Profit & Loss");

        var currentRow = 1;
        currentRow = RenderMetadata(worksheet, dataset.Metadata, currentRow);
        currentRow++;
        currentRow = RenderSummary(worksheet, dataset.Summary, currentRow);
        currentRow++;

        var headerRow = currentRow;
        RenderHeaders(worksheet, headerRow);

        var dataRow = headerRow + 1;
        foreach (var row in dataset.Rows)
        {
            RenderRow(worksheet, row, dataRow);
            dataRow++;
        }

        ApplyPolish(worksheet, headerRow, dataRow - 1);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);

        return Task.FromResult(new ProfitLossExportResult(
            stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            BuildFileName(dataset.Metadata)));
    }

    private static int RenderMetadata(IXLWorksheet worksheet, ProfitLossExportMetadataDto metadata, int startRow)
    {
        worksheet.Cell(startRow, 1).Value = "Shop:";
        worksheet.Cell(startRow, 2).Value = metadata.ShopName;
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Address:";
        worksheet.Cell(startRow, 2).Value = metadata.ShopAddress ?? string.Empty;
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Period:";
        worksheet.Cell(startRow, 2).Value = $"{metadata.From:yyyy-MM-dd} to {metadata.To:yyyy-MM-dd}";
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Type:";
        worksheet.Cell(startRow, 2).Value = metadata.Type;
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Search:";
        worksheet.Cell(startRow, 2).Value = metadata.Search ?? string.Empty;
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Generated:";
        worksheet.Cell(startRow, 2).Value = metadata.GeneratedAt.UtcDateTime;
        worksheet.Cell(startRow, 2).Style.DateFormat.Format = "yyyy-MM-dd HH:mm";
        worksheet.Cell(startRow++, 1).Style.Font.Bold = true;

        worksheet.Cell(startRow, 1).Value = "Generated By:";
        worksheet.Cell(startRow, 2).Value = metadata.GeneratedBy;
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;

        return startRow;
    }

    private static int RenderSummary(IXLWorksheet worksheet, ProfitLossExportSummaryDto summary, int startRow)
    {
        worksheet.Cell(startRow, 1).Value = "Summary";
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        WriteSummaryRow(worksheet, startRow++, "Net Profit After Tax", summary.NetProfitAfterTax, true);
        WriteSummaryRow(worksheet, startRow++, "Revenue Including Tax", summary.RevenueIncludingTax, true);
        WriteSummaryRow(worksheet, startRow++, "Total Cost", summary.TotalCost, true);
        WriteSummaryRow(worksheet, startRow++, "Average Margin %", summary.AverageMarginPercent, false);
        WriteSummaryRow(worksheet, startRow++, "Invoice Count", summary.InvoiceCount, false);
        WriteSummaryRow(worksheet, startRow++, "Return Count", summary.ReturnCount, false);
        WriteSummaryRow(worksheet, startRow, "Adjustment Count", summary.AdjustmentCount, false);

        return startRow;
    }

    private static void WriteSummaryRow(IXLWorksheet worksheet, int row, string label, decimal value, bool currency)
    {
        worksheet.Cell(row, 1).Value = label;
        worksheet.Cell(row, 2).Value = value;
        worksheet.Cell(row, 2).Style.NumberFormat.Format = currency ? "#,##0.00" : "0.##";
    }

    private static void WriteSummaryRow(IXLWorksheet worksheet, int row, string label, decimal? value, bool currency)
    {
        worksheet.Cell(row, 1).Value = label;
        worksheet.Cell(row, 2).Value = value ?? 0m;
        worksheet.Cell(row, 2).Style.NumberFormat.Format = currency ? "#,##0.00" : "0.##";
    }

    private static void WriteSummaryRow(IXLWorksheet worksheet, int row, string label, int value, bool currency)
    {
        worksheet.Cell(row, 1).Value = label;
        worksheet.Cell(row, 2).Value = value;
        worksheet.Cell(row, 2).Style.NumberFormat.Format = currency ? "#,##0.00" : "0";
    }

    private static void RenderHeaders(IXLWorksheet worksheet, int row)
    {
        var headers = new[]
        {
            "Reference",
            "Date",
            "Type",
            "Customer",
            "Total Cost",
            "Wastage Cost",
            "Revenue Excluding Tax",
            "Revenue Including Tax",
            "Profit Before Tax",
            "Profit After Tax",
            "Margin %",
        };

        for (var i = 0; i < headers.Length; i++)
        {
            worksheet.Cell(row, i + 1).Value = headers[i];
            worksheet.Cell(row, i + 1).Style.Font.Bold = true;
            worksheet.Cell(row, i + 1).Style.Font.FontColor = XLColor.White;
            worksheet.Cell(row, i + 1).Style.Fill.BackgroundColor = XLColor.FromHtml("#2D4A87");
            worksheet.Cell(row, i + 1).Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
        }
    }

    private static void RenderRow(IXLWorksheet worksheet, ProfitLossExportRowDto row, int rowNumber)
    {
        worksheet.Cell(rowNumber, 1).Value = row.ReferenceNumber;
        worksheet.Cell(rowNumber, 2).Value = row.OccurredAt.UtcDateTime;
        worksheet.Cell(rowNumber, 2).Style.DateFormat.Format = "yyyy-MM-dd HH:mm";
        worksheet.Cell(rowNumber, 3).Value = row.RowType;
        worksheet.Cell(rowNumber, 4).Value = row.CustomerName ?? string.Empty;
        worksheet.Cell(rowNumber, 5).Value = row.TotalCost;
        worksheet.Cell(rowNumber, 6).Value = row.WastageCost;
        worksheet.Cell(rowNumber, 7).Value = row.RevenueBeforeTax;
        worksheet.Cell(rowNumber, 8).Value = row.RevenueAfterTax;
        worksheet.Cell(rowNumber, 9).Value = row.ProfitBeforeTax;
        worksheet.Cell(rowNumber, 10).Value = row.ProfitAfterTax;
        worksheet.Cell(rowNumber, 11).Value = row.MarginPercent ?? 0m;

        for (var col = 5; col <= 11; col++)
        {
            worksheet.Cell(rowNumber, col).Style.NumberFormat.Format = col == 11 ? "0.##" : "#,##0.00";
        }
    }

    private static void ApplyPolish(IXLWorksheet worksheet, int headerRow, int lastDataRow)
    {
        worksheet.SheetView.FreezeRows(headerRow);
        worksheet.Range(headerRow, 1, headerRow, 11).SetAutoFilter();
        worksheet.Columns(1, 11).AdjustToContents();

        for (var col = 1; col <= 11; col++)
        {
            if (worksheet.Column(col).Width < 12)
            {
                worksheet.Column(col).Width = 12;
            }
        }

        if (lastDataRow >= headerRow + 1)
        {
            worksheet.Range(headerRow + 1, 1, lastDataRow, 11).Style.Alignment.Vertical = XLAlignmentVerticalValues.Center;
        }
    }

    private static string BuildFileName(ProfitLossExportMetadataDto metadata)
    {
        var sanitizedShop = SanitizeShopName(metadata.ShopName);
        return $"{sanitizedShop}-profit-loss-{metadata.From:yyyy-MM-dd}-to-{metadata.To:yyyy-MM-dd}.xlsx";
    }

    private static string SanitizeShopName(string shopName)
    {
        var lower = shopName.ToLowerInvariant();
        var withHyphens = Regex.Replace(lower, @"\s+", "-");
        var safe = Regex.Replace(withHyphens, @"[^a-z0-9\-]", string.Empty);
        var collapsed = Regex.Replace(safe, "-{2,}", "-");
        var trimmed = collapsed.Trim('-');
        return string.IsNullOrEmpty(trimmed) ? "shop" : trimmed;
    }
}
