using ClosedXML.Excel;

using Intelibill.Application.Features.Exports.Sales;
using Intelibill.Application.Features.Exports.Sales.DTOs;

namespace Intelibill.Infrastructure.Services.Exports;

public sealed class SalesExcelExportRenderer : ISalesExcelExportRenderer
{
    public Task<SalesExportResult> RenderAsync(SalesExportDatasetDto dataset, CancellationToken cancellationToken)
    {
        using var workbook = new XLWorkbook();

        return string.Equals(dataset.Metadata.ExportLevel, SalesExportLevel.LineItems, StringComparison.OrdinalIgnoreCase)
            ? SalesExcelLineItemRenderer.RenderLineItemsAsync(workbook, dataset)
            : SalesExcelSummaryRenderer.RenderSummaryAsync(workbook, dataset);
    }

    internal static int RenderMetadata(IXLWorksheet worksheet, SalesExportMetadataDto metadata, int startRow)
    {
        worksheet.Cell(startRow, 1).Value = "Shop:";
        worksheet.Cell(startRow, 2).Value = metadata.ShopName;
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        worksheet.Cell(startRow, 1).Value = "Address:";
        worksheet.Cell(startRow, 2).Value = metadata.ShopAddress;
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        worksheet.Cell(startRow, 1).Value = "Period:";
        worksheet.Cell(startRow, 2).Value = $"{metadata.StartDate:yyyy-MM-dd} to {metadata.EndDate:yyyy-MM-dd}";
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        worksheet.Cell(startRow, 1).Value = "Generated:";
        worksheet.Cell(startRow, 2).Value = metadata.GeneratedAt.DateTime;
        worksheet.Cell(startRow, 2).Style.DateFormat.Format = "yyyy-MM-dd HH:mm";
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        worksheet.Cell(startRow, 1).Value = "Generated By:";
        worksheet.Cell(startRow, 2).Value = metadata.GeneratedBy;
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;
        startRow++;

        worksheet.Cell(startRow, 1).Value = "Level:";
        worksheet.Cell(startRow, 2).Value = metadata.ExportLevel;
        worksheet.Cell(startRow, 1).Style.Font.Bold = true;

        return startRow;
    }
}
