// <auto-generated />
using System;
using Intelibill.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intelibill.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424174207_AddCustomerLedgerAndSalePaymentSplit")]
    partial class AddCustomerLedgerAndSalePaymentSplit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intelibill.Domain.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("account_type");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bank_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ifsc_code");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bank_accounts");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_bank_accounts_owner_user_id");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_customers_owner_user_id");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("ix_customers_owner_user_id_is_active");

                    b.HasIndex("OwnerUserId", "PhoneNumber")
                        .HasDatabaseName("ix_customers_owner_user_id_phone_number");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.CustomerLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customer_ledger_entries");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_ledger_entries_customer_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_customer_ledger_entries_sale_id");

                    b.HasIndex("ShopId", "CustomerId", "EntryDate")
                        .HasDatabaseName("ix_customer_ledger_entries_shop_id_customer_id_entry_date");

                    b.HasIndex("ShopId", "SaleId", "EntryType")
                        .HasDatabaseName("ix_customer_ledger_entries_shop_id_sale_id_entry_type");

                    b.ToTable("customer_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_customer_ledger_entries_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_customer_ledger_entries_sale_by_type", "((entry_type = 'SALE_DUE' AND sale_id IS NOT NULL) OR (entry_type = 'PAYMENT_RECEIVED' AND sale_id IS NULL))");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<bool>("IsVoided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voided");

                    b.Property<Guid?>("OriginalExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_expense_id");

                    b.Property<string>("PaidTo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("paid_to");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<Guid?>("SupplierLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_ledger_entry_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_expenses_category_id");

                    b.HasIndex("OriginalExpenseId")
                        .HasDatabaseName("ix_expenses_original_expense_id");

                    b.HasIndex("SupplierLedgerEntryId")
                        .HasDatabaseName("ix_expenses_supplier_ledger_entry_id");

                    b.HasIndex("ShopId", "ExpenseDate")
                        .HasDatabaseName("ix_expenses_shop_id_expense_date");

                    b.HasIndex("ShopId", "IsVoided")
                        .HasDatabaseName("ix_expenses_shop_id_is_voided");

                    b.HasIndex("ShopId", "PaidTo")
                        .HasDatabaseName("ix_expenses_shop_id_paid_to");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expense_categories");

                    b.HasIndex("ShopId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_expense_categories_shop_id_name");

                    b.ToTable("expense_categories", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<decimal>("MaxLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("max_level");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("reorder_level");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory");

                    b.HasIndex("ItemId", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_item_id_shop_id");

                    b.HasIndex("ShopId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_shop_id_item_id");

                    b.ToTable("inventory", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_max_non_negative", "max_level >= 0");

                            t.HasCheckConstraint("ck_inventory_quantity_non_negative", "quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_reorder_lte_max", "reorder_level <= max_level");

                            t.HasCheckConstraint("ck_inventory_reorder_non_negative", "reorder_level >= 0");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("batch_number");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsVoided")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_voided");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateOnly?>("ManufacturingDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacturing_date");

                    b.Property<decimal>("Mrp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mrp");

                    b.Property<decimal>("OriginalQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("original_quantity");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SalesPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sales_price");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<bool>("TaxIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tax_included");

                    b.Property<decimal>("TaxRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate_percent");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_inventory_batches");

                    b.HasAlternateKey("Id", "ItemId", "ShopId")
                        .HasName("ak_inventory_batches_id_item_id_shop_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_inventory_batches_supplier_id");

                    b.HasIndex("ItemId", "ShopId")
                        .HasDatabaseName("ix_inventory_batches_item_id_shop_id");

                    b.HasIndex("ShopId", "ExpiryDate")
                        .HasDatabaseName("ix_inventory_batches_shop_id_expiry_date");

                    b.HasIndex("ShopId", "SupplierId")
                        .HasDatabaseName("ix_inventory_batches_shop_id_supplier_id");

                    b.HasIndex("Id", "ItemId", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_batches_id_item_id_shop_id");

                    b.HasIndex("ShopId", "ItemId", "BatchNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_batches_shop_id_item_id_batch_number")
                        .HasFilter("is_voided = false");

                    b.ToTable("inventory_batches", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_batches_quantity_non_negative", "quantity >= 0");

                            t.HasCheckConstraint("ck_inventory_batches_sales_lte_mrp", "sales_price <= mrp");

                            t.HasCheckConstraint("ck_inventory_batches_tax_rate_range", "tax_rate_percent >= 0 AND tax_rate_percent <= 100");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("uom");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasAlternateKey("Id", "ShopId")
                        .HasName("ak_items_id_shop_id");

                    b.HasIndex("Id", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("ix_items_id_shop_id");

                    b.HasIndex("ShopId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_items_shop_id_barcode");

                    b.HasIndex("ShopId", "IsActive")
                        .HasDatabaseName("ix_items_shop_id_is_active");

                    b.HasIndex("ShopId", "Name")
                        .HasDatabaseName("ix_items_shop_id_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal>("DueAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("due_amount");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TotalTaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_tax_amount");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_customer_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_sales_shop_id");

                    b.HasIndex("ShopId", "CustomerId")
                        .HasDatabaseName("ix_sales_shop_id_customer_id");

                    b.HasIndex("ShopId", "InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_shop_id_invoice_number");

                    b.HasIndex("ShopId", "SoldAt")
                        .HasDatabaseName("ix_sales_shop_id_sold_at");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost_price");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasPriceMismatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_price_mismatch");

                    b.Property<Guid>("InventoryBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_batch_id");

                    b.Property<bool>("IsPriceIncludingTax")
                        .HasColumnType("boolean")
                        .HasColumnName("is_price_including_tax");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Mrp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("mrp");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("SalesPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sales_price");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<decimal>("TaxRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate_percent");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sale_items");

                    b.HasIndex("InventoryBatchId")
                        .HasDatabaseName("ix_sale_items_inventory_batch_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_sale_items_item_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_items_sale_id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_sale_items_shop_id");

                    b.HasIndex("ShopId", "ItemId")
                        .HasDatabaseName("ix_sale_items_shop_id_item_id");

                    b.ToTable("sale_items", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contact_person");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GstNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gst_number");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mobile_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.ShopMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_shop_memberships");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_memberships_shop_id");

                    b.HasIndex("UserId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_memberships_user_id_is_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("UserId", "LastUsedAt")
                        .HasDatabaseName("ix_shop_memberships_user_id_last_used_at");

                    b.HasIndex("UserId", "ShopId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_memberships_user_id_shop_id");

                    b.ToTable("shop_memberships", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("InventoryBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_batch_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference_number");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_stock_transactions");

                    b.HasIndex("ItemId", "ShopId")
                        .HasDatabaseName("ix_stock_transactions_item_id_shop_id");

                    b.HasIndex("InventoryBatchId", "ItemId", "ShopId")
                        .HasDatabaseName("ix_stock_transactions_inventory_batch_id_item_id_shop_id");

                    b.HasIndex("ShopId", "InventoryBatchId", "PerformedAt")
                        .HasDatabaseName("ix_stock_transactions_shop_id_inventory_batch_id_performed_at");

                    b.HasIndex("ShopId", "ItemId", "PerformedAt")
                        .HasDatabaseName("ix_stock_transactions_shop_id_item_id_performed_at");

                    b.ToTable("stock_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_transactions_quantity_non_zero", "quantity <> 0");

                            t.HasCheckConstraint("ck_stock_transactions_quantity_sign_by_type", "((transaction_type IN ('IN', 'RET') AND quantity > 0) OR (transaction_type IN ('OUT', 'REJ', 'DMG', 'STOL') AND quantity < 0) OR (transaction_type = 'ADJ'))");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("contact_person_name");

                    b.Property<string>("ContactPersonPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_person_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preferred");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Pin")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("pin");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_suppliers_owner_user_id");

                    b.HasIndex("OwnerUserId", "IsActive")
                        .HasDatabaseName("ix_suppliers_owner_user_id_is_active");

                    b.HasIndex("OwnerUserId", "IsSystem")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_owner_user_id_is_system")
                        .HasFilter("is_system = true");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.SupplierLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_supplier_ledger_entries");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_supplier_ledger_entries_batch_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_ledger_entries_supplier_id");

                    b.HasIndex("ShopId", "BatchId", "EntryType")
                        .HasDatabaseName("ix_supplier_ledger_entries_shop_id_batch_id_entry_type");

                    b.HasIndex("ShopId", "SupplierId", "EntryDate")
                        .HasDatabaseName("ix_supplier_ledger_entries_shop_id_supplier_id_entry_date");

                    b.ToTable("supplier_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_ledger_entries_amount_non_zero", "amount <> 0");

                            t.HasCheckConstraint("ck_supplier_ledger_entries_batch_by_type", "((entry_type = 'GOODS_RECEIVED' AND batch_id IS NOT NULL) OR (entry_type IN ('PAYMENT_MADE', 'RECORD_ADJUSTED') AND batch_id IS NULL))");
                        });
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsLoginEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_login_enabled");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en-IN")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number")
                        .HasFilter("phone_number IS NOT NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_email");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_key");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_external_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_external_logins_user_id");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_logins_provider_provider_key");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_accounts_users_owner_user_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_users_owner_user_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.CustomerLedgerEntry", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_ledger_entries_customers_customer_id");

                    b.HasOne("Intelibill.Domain.Entities.Sale", null)
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customer_ledger_entries_sales_sale_id");

                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_ledger_entries_shops_shop_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Expense", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.ExpenseCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_expense_categories_category_id");

                    b.HasOne("Intelibill.Domain.Entities.Expense", null)
                        .WithMany()
                        .HasForeignKey("OriginalExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_expenses_expenses_original_expense_id");

                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.SupplierLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("SupplierLedgerEntryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_supplier_ledger_entries_supplier_ledger_entry_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.ExpenseCategory", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_categories_shops_shop_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.Item", "Item")
                        .WithOne("Inventory")
                        .HasForeignKey("Intelibill.Domain.Entities.Inventory", "ItemId", "ShopId")
                        .HasPrincipalKey("Intelibill.Domain.Entities.Item", "Id", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_item_id_shop_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.InventoryBatch", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_batches_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_batches_suppliers_supplier_id");

                    b.HasOne("Intelibill.Domain.Entities.Item", "Item")
                        .WithMany("Batches")
                        .HasForeignKey("ItemId", "ShopId")
                        .HasPrincipalKey("Id", "ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_batches_items_item_id_shop_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Item", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_shops_shop_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sales_customers_customer_id");

                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_shops_shop_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.InventoryBatch", null)
                        .WithMany()
                        .HasForeignKey("InventoryBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_inventory_batches_inventory_batch_id");

                    b.HasOne("Intelibill.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_items_item_id");

                    b.HasOne("Intelibill.Domain.Entities.Sale", null)
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_sales_sale_id");

                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_shops_shop_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.ShopMembership", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", "Shop")
                        .WithMany("Memberships")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_memberships_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.User", "User")
                        .WithMany("ShopMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shop_memberships_users_user_id");

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.Item", "Item")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ItemId", "ShopId")
                        .HasPrincipalKey("Id", "ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_items_item_id_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.InventoryBatch", "InventoryBatch")
                        .WithMany("StockTransactions")
                        .HasForeignKey("InventoryBatchId", "ItemId", "ShopId")
                        .HasPrincipalKey("Id", "ItemId", "ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_inventory_batches_inventory_batch_id_ite");

                    b.Navigation("InventoryBatch");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Supplier", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_users_owner_user_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.SupplierLedgerEntry", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.InventoryBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_supplier_ledger_entries_inventory_batches_batch_id");

                    b.HasOne("Intelibill.Domain.Entities.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_ledger_entries_shops_shop_id");

                    b.HasOne("Intelibill.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_ledger_entries_suppliers_supplier_id");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("Intelibill.Domain.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_external_logins_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.InventoryBatch", b =>
                {
                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Item", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Inventory");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.Shop", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Intelibill.Domain.Entities.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("ShopMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
